name: 'Git Flow Action'
description: 'GithHub Action for checking the base branch of a pull request.'
inputs:
  main_branch_pattern:
    description: 'Main branch pattern'
    required: true
    default: '^(main|master)$'
  development_branch_pattern:
    description: 'Development branch pattern'
    required: true
    default: '^(dev|develop|development)$'
  semestry_staging_branch_pattern:
    description: 'Semestry staging branch pattern'
    required: true
    default: '^([0-9]+(\.[0-9]+)+-staging|development-staging)$'
  semestry_testing_branch_pattern:
    description: 'Semestry Testing branch pattern'
    required: true
    default: '^([0-9]+(\.[0-9]+)+-test|development-test)$'
  feature_branch_prefix:
    description: 'Feature branch prefix'
    required: true
    default: 'feature/'
  hotfix_branch_prefix:
    description: 'Hotfix branch prefix'
    required: true
    default: 'hotfix/'
  fix_branch_prefix:
    description: 'Fix branch prefix'
    required: true
    default: 'fix/'
  staging_branch_prefix:
    description: 'Staging branch prefix'
    required: true
    default: 'staging/'
runs:
  using: 'node20'
  main: 'index.js'
